version: '3'
services:

  api:
    build: ./Testing.Api
    ports:
     - "5000:5000"
    networks:
     - "monitoring"

  graphite:
    image: "graphiteapp/graphite-statsd"
    ports:
     - "81:81"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"
    networks:
     - "monitoring"

  grafana:
    image: "grafana/grafana"
    ports:
     - "3000:3000"
    networks:
     - "monitoring"
     
  acceptance:
    build: ./Testing.Api.AcceptanceTests
    environment:
     - StatsdHost=graphite
     - ApiHost=http://api:5000
    networks:
     - "monitoring"


networks:
  monitoring: