version: '3'
services:

  api:
    build: ./Testing.Boilerplate.Api
    ports:
     - "5000:5000"
    networks:
     - "monitoring"

  graphite:
    image: "graphiteapp/graphite-statsd"
    ports:
     - "80:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125"
     - "8126:8126"
    networks:
     - "monitoring"

  grafana:
    image: "grafana/grafana"
    ports:
     - "3000:3000"
    networks:
     - "monitoring"

networks:
  monitoring: